# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f36d08368313a3813e5a06fefc256152196934a70ec7b83fd5a84d47b36c8d76660720cbb862eb9d6b159f9c3211db6ca575cd5d6b04c54c97c1d68cf60fe059

test:
  secret_key_base: 0119903abb4d0c8020a0a39e897e116c12c6ae501b5b61ef3cb22d993941d6ac53f6039a3adcaee5837489d20b7b07991d0f5b2f4f33b2d23afb7fe18ddbd5e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
